# Generated by Django 4.0.2 on 2022-02-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customer_profile_pic_alter_customer_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
